version: "3"
services:
  chat:
    build: .
    ports:
    - 8080
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/html:/usr/share/nginx/html
    restart: always
    ports:
      - 80:80
    depends_on:
      - chat
